#!/bin/sh

# CROSS_COMPILE=arm-none-eabi- make stm32f4-discovery_defconfig &&
CROSS_COMPILE=arm-none-eabi- make all -j4 &&
arm-none-eabi-objcopy -O ihex u-boot u-boot.hex &&
st-flash --reset write u-boot.bin  0x08000000 
